### PR TITLE
Making our project page more convenient to navigate

### PR DESCRIPTION
**Pull request by Juliuus**
Hi! I am Yuliya Gustap, I have completed the DEDA seminar in SoSe2020. 

Now I want to add our presentation here, so that the reader could check out the presentation along with the code. In order to make the page more readable in general, I created a README.md file with summary of the project. No changes were made to the code.

I have attached the link to this page to my CV, so I would be greatfull if you accepted the changes. 

Thank you in advance!
Yuliya

### CODE REVIEW

**Comment by lizzzi111** [comment]
Hi Yuliya,

I do not mind adding the presentation to the repo or some additional info to the README file, however, it should still conform to our format. You could update the already existing README file with your additional info if you want (e.g. just append your text or paste it in the middle of README.md file for example before the R Code section). But your quantlet should still contain LvB styled README.md - otherwise, it is not a quanlet. If you have questions - contact me here or via email. 
Best regards,
Liza from the Quantlet Team.

**Comment by Juliuus** [comment]
Hi Liza,

Hope you are well and healthy!

I tried to follow your reccomendations regarding the README.md file. 

The main thing for me is to upload the presentation to the page, so let me know if I should correct something else to do it. 

Thank you!

Yuliya

**Comment by lizzzi111** [comment]
Hi Yuliya,

now all of the spaces in your code (in the README) got lost, unfortunately. I cannot accept only one thing without accepting the other - it is technically impossible. So what I can offer you. I close this pull request - you just upload the file and create the pull request only for this presentation file. Which I will most likely directly accept. And afterward, we will sort out the thing with Readme: you will either send me the text and I will paste it inside the READMe myself or you will create another pull-request for it, without losing the spaces in the code and YAML. 

Best,
Liza

**Comment by Juliuus** [comment]
Hi Liza,

I deleted the README.md file. Is it okay this way? 

Here is the text that I wanted to have in README. I would appreaciate if you could please add it to the existing README:


For the R code see: *Cryptocurrencies in Portfolio Management: final code.R*  
For the presentation see: *Presentation Role of CCs in Portfolio Management.pdf*
# Project Description
In this project Yuliya Gustap and Arash Moussavi together with the Blockchain Research Center of Humboldt University of Berlin attempted to determine the effects of introducing cryptocurrencies into a traditional diversified portfolio, which includes stocks, fixed income, commodities and currencies.
*CRIX* - the diversified crytocurrency index - was used as a proxy of the whole cryptocurrency universe. 
The total of four portfolios were estimated using the Maximum Diversification rule: two portfolios estimated by Dynamic Conditional Correlation GARCH (DCC-GARCH) with and without CRIX, and two more portfolios estimated by Assymtric Dynamic Conditional Correlation GARCH (ADCC-GARCH) with and without CRIX. 

# Project Results
The two portfolios with CRIX (both DCC-GARCH and ADCC-GARCH) outperformed on several metrics, such as mean return, coefficient of variation, Sharpe and Sortino ratio. 
However, they also demonstrated higher standard deviation and higher maximum drawdown than portfolios without CRIX. 
*The results imply that although including cryptocurrrencies into a traditional portfolio increases it's risk, it increases the ruturn by a higher degree, leading to higher risk-adjusted return.*



Many thanks!  
Yuliya

**Comment by lizzzi111** [comment]
Hi Yuliya,

I added the text and confirmed the pull-request.

Best,

Liza.

**Pull request merged**
